name: projetCv

on:
  push:
    branches:
      - main  # ou master, selon votre branche principale

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: installation
        run: echo 'install dependecies'
      
      
