name: projetCv

on:
  push:
    branches:
      - main  # ou master, selon votre branche principale

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: installation
        run: echo 'install dependecies'
      
      
